using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using WWB.BinarySerializer.Generator.Emission;

namespace WWB.BinarySerializer.Generator;

[Generator]
public sealed class BinarySerializerGenerator : IIncrementalGenerator
{
    private const string Contract = "WWB.BinarySerializer.Attributes.BinaryContractAttribute";
    private const string Property = "WWB.BinarySerializer.Attributes.BinaryFieldAttribute";
    private static readonly DiagnosticDescriptor AccessorError = new("WWB001", "Invalid property accessors", "属性 '{0}' 必须同时具有公共 getter 和 setter", "BinarySerializer", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor UnsupportedError = new("WWB003", "Unsupported type", "属性 '{0}' 的类型当前不支持 Source Generator", "BinarySerializer", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor ConstructorError = new("WWB004", "Missing public constructor", "类型 '{0}' 必须具有公共无参构造函数", "BinarySerializer", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor CyclicError = new("WWB005", "Cyclic object graph", "类型 '{0}' 的属性图包含循环引用，Source Generator 暂不支持", "BinarySerializer", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contracts = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node)!)
            .Where(static type => type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == Contract)
                || type.GetMembers().OfType<IPropertySymbol>().Any(p => p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == Property)));
        var options = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) => provider.GlobalOptions);
        context.RegisterSourceOutput(contracts.Combine(options), static (production, pair) => Emit(production, pair.Left, pair.Right));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol type, AnalyzerConfigOptions options)
    {
        var properties = SerializedProperties(type)
            .OrderBy(x => Order(x.Attribute)).ThenBy(x => x.Property.Locations[0].SourceSpan.Start)
            .ToArray();

        var invalid = FindInvalid(type, new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default));
        if (invalid != null)
        {
            var diagnosticsDisabled = DiagnosticsDisabled(options);
            if (!diagnosticsDisabled)
            {
                var descriptor = invalid.GetMethod?.DeclaredAccessibility != Accessibility.Public || invalid.SetMethod?.DeclaredAccessibility != Accessibility.Public
                    ? AccessorError
                    : UnsupportedError;
                context.ReportDiagnostic(Diagnostic.Create(descriptor, invalid.Locations.FirstOrDefault(), invalid.Name));
            }
            return;
        }
        if (properties.Length == 0) return;
        if (!type.InstanceConstructors.Any(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length == 0))
        {
            if (!DiagnosticsDisabled(options)) context.ReportDiagnostic(Diagnostic.Create(ConstructorError, type.Locations.FirstOrDefault(), type.ToDisplayString()));
            return;
        }
        if (HasCycle(type))
        {
            if (!DiagnosticsDisabled(options)) context.ReportDiagnostic(Diagnostic.Create(CyclicError, type.Locations.FirstOrDefault(), type.ToDisplayString()));
            return;
        }

        var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var className = GeneratedName(type) + "__Codec";
        var contract = type.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == Contract);
        var endian = EnumValue(contract, "EndianType", "Little");
        var source = new StringBuilder("// <auto-generated />\nusing System.Runtime.CompilerServices;\n");
        source.AppendLine("namespace " + (type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString()) + ";");
        source.AppendLine($"public sealed class {className} : global::WWB.BinarySerializer.IBinaryCodec<{fullName}>, global::WWB.BinarySerializer.IEndianAwareCodec {{");
        source.AppendLine($"public bool BigEndian => {(endian == "Big" ? "true" : "false")};");
        source.AppendLine($"public void Encode(global::WWB.BinarySerializer.Buffers.BufferWriter writer, {fullName} value, global::WWB.BinarySerializer.SerializationContext context) {{ global::System.ArgumentNullException.ThrowIfNull(writer); global::System.ArgumentNullException.ThrowIfNull(value);");
        foreach (var item in properties) FieldEmitter.Write(source, item.Property, item.Attribute);
        source.AppendLine("}");
        source.AppendLine($"public {fullName} Decode(ref global::WWB.BinarySerializer.Buffers.BufferReader reader, global::WWB.BinarySerializer.SerializationContext context) {{ var value = new {fullName}();");
        foreach (var item in properties) FieldEmitter.Read(source, item.Property, item.Attribute);
        source.AppendLine("return value; }");
        source.AppendLine($"internal static class {className}Registration {{ [ModuleInitializer] internal static void Register() {{ global::WWB.BinarySerializer.GeneratedCodecRegistry<{fullName}>.TryRegister(new {className}()); }} }} }}");
        context.AddSource(className + ".g.cs", source.ToString());
    }

    private static IEnumerable<(IPropertySymbol Property, AttributeData Attribute)> SerializedProperties(INamedTypeSymbol type)
        => type.GetMembers().OfType<IPropertySymbol>()
            .Select(p => (Property: p, Attribute: p.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == Property)))
            .Where(x => x.Attribute != null && !IsIgnored(x.Attribute!))
            .Select(x => (x.Property, Attribute: x.Attribute!));

    private static IPropertySymbol? FindInvalid(INamedTypeSymbol type, HashSet<INamedTypeSymbol> visited)
    {
        if (!visited.Add(type)) return null;
        foreach (var (property, attribute) in SerializedProperties(type))
        {
            if (!CanGenerate(property, attribute)) return property;
            var propertyType = property.Type;
            if (TypeShape.IsObject(propertyType))
            {
                var nested = FindInvalid((INamedTypeSymbol)propertyType, visited);
                if (nested != null) return nested;
            }
            else if (!TypeShape.IsByteArray(propertyType) && TypeShape.IsCollection(propertyType, out var element) && TypeShape.IsObject(element))
            {
                var nested = FindInvalid((INamedTypeSymbol)element, visited);
                if (nested != null) return nested;
            }
        }
        return null;
    }

    private static bool HasCycle(INamedTypeSymbol type) => HasCycle(type, new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default), new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default));

    private static bool HasCycle(INamedTypeSymbol type, HashSet<INamedTypeSymbol> visited, HashSet<INamedTypeSymbol> path)
    {
        if (path.Contains(type)) return true;
        if (visited.Contains(type)) return false;
        visited.Add(type);
        path.Add(type);
        foreach (var (property, _) in SerializedProperties(type))
        {
            var propertyType = property.Type;
            if (TypeShape.IsObject(propertyType) && HasCycle((INamedTypeSymbol)propertyType, visited, path)) return true;
            if (!TypeShape.IsByteArray(propertyType) && TypeShape.IsCollection(propertyType, out var element) && TypeShape.IsObject(element) && HasCycle((INamedTypeSymbol)element, visited, path)) return true;
        }
        path.Remove(type);
        return false;
    }

    private static bool CanGenerate(IPropertySymbol property, AttributeData attribute)
    {
        if (property.GetMethod?.DeclaredAccessibility != Accessibility.Public || property.SetMethod?.DeclaredAccessibility != Accessibility.Public) return false;
        if (ValueCodecName(attribute) != null) return true;
        ITypeSymbol? element = null;
        var isCollection = !TypeShape.IsByteArray(property.Type) && TypeShape.IsCollection(property.Type, out element);
        if (isCollection)
        {
            if (!(TypeShape.IsScalar(element!) || element!.TypeKind == TypeKind.Enum || TypeShape.IsObject(element!))) return false;
        }
        else if (!TypeShape.IsScalar(property.Type) && property.Type.TypeKind != TypeKind.Enum && !TypeShape.IsObject(property.Type)) return false;
        return true;
    }
    private static string? ValueCodecName(AttributeData attribute) =>
        attribute.NamedArguments.FirstOrDefault(x => x.Key == "ValueCodecName").Value.Value as string;

    private static string GeneratedName(INamedTypeSymbol type)
    {
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
        var chars = name.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        return new string(chars);
    }
    private static bool IsIgnored(AttributeData attribute) => attribute.NamedArguments.Any(x => x.Key == "Ignore" && x.Value.Value is true);
    private static bool DiagnosticsDisabled(AnalyzerConfigOptions options)
    {
        var disabled = (options.TryGetValue("build_property.DisableBinarySerializerDiagnostics", out var flag) || options.TryGetValue("build_property.disablebinaryserializerdiagnostics", out flag)) && string.Equals(flag, "true", System.StringComparison.OrdinalIgnoreCase);
        return disabled || (options.TryGetValue("build_property.IsTestProject", out var testProject) && string.Equals(testProject, "true", System.StringComparison.OrdinalIgnoreCase));
    }
    private static int Order(AttributeData attribute) => attribute.ConstructorArguments.Length == 0 ? 0 : (int)attribute.ConstructorArguments[0].Value!;
    private static string EnumValue(AttributeData? attribute, string name, string fallback) => attribute?.NamedArguments.FirstOrDefault(x => x.Key == name).Value.Value is int value && value != 0 ? "Big" : fallback;
}
